export const families = [
  {
    id: 1,
    name: 'Rodriguez Family',
    slug: 'rodriguez-family',
    description: 'A proud lineage of artists, educators, and community leaders spanning five generations in Manila, Philippines.',
    motto: 'Unity is Strength, Love is Legacy',
    cover_photo: null,
    member_count: 12,
  },
  {
    id: 2,
    name: 'Chen Dynasty',
    slug: 'chen-dynasty',
    description: 'Tracing our roots from Fujian province to modern-day Singapore, the Chen family legacy of entrepreneurship and philanthropy.',
    motto: 'Honor the Past, Build the Future',
    cover_photo: null,
    member_count: 8,
  },
  {
    id: 3,
    name: 'Thompson Lineage',
    slug: 'thompson-lineage',
    description: 'From Scottish highlands to the American Midwest, the Thompson story is one of resilience, hard work, and family bonds.',
    motto: 'Ever Forward',
    cover_photo: null,
    member_count: 15,
  },
]

export const members = [
  // === Rodriguez Family (family_id: 1) ===
  {
    id: 1,
    family_id: 1,
    full_name: 'Alejandro Rodriguez Sr.',
    nickname: 'Don Alejo',
    slug: 'alejandro-rodriguez-sr',
    gender: 'male',
    date_of_birth: '1920-03-15',
    date_of_death: '2010-11-02',
    place_of_birth: 'Manila, Philippines',
    place_of_death: 'Manila, Philippines',
    biography: 'Alejandro Rodriguez Sr. was a respected educator and school principal who dedicated his life to improving education in rural Philippines. He founded three public schools and mentored countless teachers throughout his 40-year career. His passion for learning and community service set the foundation for the Rodriguez family values.',
    occupation: 'Educator / School Principal',
    education: 'Bachelor of Education, University of Santo Tomas; Master of Arts in Education, University of the Philippines',
    awards: 'Presidential Merit Award for Education (1985), Lifetime Achievement in Teaching (2000)',
    hobbies: 'Reading, Gardening, Chess',
    religion: 'Roman Catholic',
    notes: null,
    profile_photo: null,
    is_deceased: 1,
    display_order: 1,
  },
  {
    id: 2,
    family_id: 1,
    full_name: 'Maria Rodriguez',
    nickname: 'Mama Mary',
    slug: 'maria-rodriguez',
    gender: 'female',
    date_of_birth: '1925-07-22',
    date_of_death: '2015-03-18',
    place_of_birth: 'Laguna, Philippines',
    place_of_death: 'Manila, Philippines',
    biography: 'Maria was the matriarch of the Rodriguez family, known for her warmth, resilience, and extraordinary culinary skills. She ran a small sari-sari store while raising seven children, instilling in them the values of hard work, faith, and family unity. Her kitchen was the heart of the home, where family stories were shared over her famous adobo.',
    occupation: 'Homemaker / Small Business Owner',
    education: null,
    awards: null,
    hobbies: 'Cooking, Gardening, Singing in the church choir',
    religion: 'Roman Catholic',
    notes: null,
    profile_photo: null,
    is_deceased: 1,
    display_order: 2,
  },
  {
    id: 3,
    family_id: 1,
    full_name: 'Alejandro Rodriguez Jr.',
    nickname: 'Alex',
    slug: 'alejandro-rodriguez-jr',
    gender: 'male',
    date_of_birth: '1950-01-10',
    date_of_death: null,
    place_of_birth: 'Manila, Philippines',
    biography: 'Alex followed in his father\'s footsteps and became a university professor. He is currently the Dean of the College of Education at Manila State University. He has authored several books on educational reform in Southeast Asia.',
    occupation: 'University Professor / Dean',
    education: 'PhD in Education, University of the Philippines; MA in Educational Leadership, Harvard University',
    awards: 'Outstanding Educator Award (2010), Fulbright Scholar (1985)',
    hobbies: 'Writing, Photography, Travel',
    religion: 'Roman Catholic',
    profile_photo: null,
    is_deceased: 0,
    display_order: 3,
  },
  {
    id: 4,
    family_id: 1,
    full_name: 'Isabella Rodriguez-Santos',
    nickname: 'Bella',
    slug: 'isabella-rodriguez-santos',
    gender: 'female',
    date_of_birth: '1953-06-05',
    date_of_death: null,
    place_of_birth: 'Manila, Philippines',
    biography: 'Isabella is a celebrated visual artist whose paintings have been exhibited in galleries across Asia and Europe. Her work often explores themes of family, identity, and Filipino heritage. She also runs a foundation that provides art scholarships underprivileged youth.',
    occupation: 'Visual Artist / Philanthropist',
    education: 'Bachelor of Fine Arts, University of Santo Tomas; MFA, Royal College of Art, London',
    awards: 'National Artist Award Nominee (2020), Asian Women Achievers Award (2015)',
    hobbies: 'Painting, Traveling, Cooking',
    religion: 'Roman Catholic',
    profile_photo: null,
    is_deceased: 0,
    display_order: 4,
  },
  {
    id: 5,
    family_id: 1,
    full_name: 'Carlos Rodriguez',
    nickname: 'Caloy',
    slug: 'carlos-rodriguez',
    gender: 'male',
    date_of_birth: '1956-11-20',
    date_of_death: '2022-08-14',
    place_of_birth: 'Manila, Philippines',
    place_of_death: 'Chicago, USA',
    biography: 'Carlos was a brilliant architect who designed some of Manila\'s most iconic buildings. He moved to Chicago later in life where he continued his practice. He was known for his modernist approach that incorporated traditional Filipino design elements.',
    occupation: 'Architect',
    education: 'Bachelor of Architecture, University of Santo Tomas; Master of Architecture, MIT',
    awards: 'Architecture Excellence Award (2005), ASEAN Design Award (2010)',
    hobbies: 'Jazz music, Photography, Sailing',
    religion: 'Roman Catholic',
    profile_photo: null,
    is_deceased: 1,
    display_order: 5,
  },
  {
    id: 6,
    family_id: 1,
    full_name: 'Sofia Rodriguez',
    nickname: 'Pia',
    slug: 'sofia-rodriguez',
    gender: 'female',
    date_of_birth: '1960-02-14',
    date_of_death: null,
    place_of_birth: 'Manila, Philippines',
    biography: 'Sofia is a renowned pediatrician who has dedicated her career to improving children\'s healthcare in rural communities. She leads a mobile clinic program that serves remote villages in the Philippines.',
    occupation: 'Pediatrician',
    education: 'Doctor of Medicine, University of the Philippines; Pediatrics Residency, Philippine General Hospital',
    awards: 'Healthcare Hero Award (2018), Outstanding Young Scientist (1995)',
    hobbies: 'Hiking, Reading, Baking',
    religion: 'Roman Catholic',
    profile_photo: null,
    is_deceased: 0,
    display_order: 6,
  },
  {
    id: 7,
    family_id: 1,
    full_name: 'Miguel Rodriguez',
    nickname: 'Migs',
    slug: 'miguel-rodriguez',
    gender: 'male',
    date_of_birth: '1980-09-30',
    date_of_death: null,
    place_of_birth: 'Manila, Philippines',
    biography: 'Miguel is a tech entrepreneur who founded a successful fintech startup. He is passionate about using technology to promote financial inclusion in Southeast Asia. He is also an active angel investor in the local startup ecosystem.',
    occupation: 'Entrepreneur / CEO',
    education: 'BS Computer Science, Ateneo de Manila University; MBA, Stanford University',
    awards: 'Forbes 30 Under 30 Asia (2015), EY Entrepreneur of the Year (2022)',
    hobbies: 'Running, Gaming, Playing guitar',
    religion: 'Roman Catholic',
    profile_photo: null,
    is_deceased: 0,
    display_order: 7,
  },
  {
    id: 8,
    family_id: 1,
    full_name: 'Lara Rodriguez-Cruz',
    nickname: 'Lara',
    slug: 'lara-rodriguez-cruz',
    gender: 'female',
    date_of_birth: '1983-04-18',
    date_of_death: null,
    place_of_birth: 'Manila, Philippines',
    biography: 'Lara is a human rights lawyer and advocate for women\'s rights. She works with an international NGO and has represented cases at the International Criminal Court. She is also a published author on legal ethics.',
    occupation: 'Human Rights Lawyer',
    education: 'BS Legal Management, Ateneo de Manila University; Juris Doctor, Harvard Law School',
    awards: 'Human Rights Defender Award (2019), International Women of Courage Award (2021)',
    hobbies: 'Yoga, Travel, Writing',
    religion: 'Roman Catholic',
    profile_photo: null,
    is_deceased: 0,
    display_order: 8,
  },
  {
    id: 9,
    family_id: 1,
    full_name: 'Alejandro Rodriguez III',
    nickname: 'Andres',
    slug: 'alejandro-rodriguez-iii',
    gender: 'male',
    date_of_birth: '2010-06-12',
    date_of_death: null,
    place_of_birth: 'Manila, Philippines',
    biography: 'Andres is the youngest of the new generation. A bright and curious student who excels in mathematics and science. He dreams of becoming an astronaut.',
    occupation: 'Student',
    education: 'Currently studying at Manila Science High School',
    awards: 'Math Olympiad Gold Medal (2024)',
    hobbies: 'Astronomy, Swimming, Coding',
    religion: 'Roman Catholic',
    profile_photo: null,
    is_deceased: 0,
    display_order: 9,
  },
  {
    id: 10,
    family_id: 1,
    full_name: 'Clara Rodriguez',
    nickname: 'Clarita',
    slug: 'clara-rodriguez',
    gender: 'female',
    date_of_birth: '2013-09-25',
    date_of_death: null,
    place_of_birth: 'Manila, Philippines',
    biography: 'Clara is a spirited young girl with a love for dance and music. She performs with the Manila Youth Ballet and has won several local dance competitions.',
    occupation: 'Student',
    education: 'Currently studying at Holy Spirit Academy',
    awards: 'National Youth Dance Competition Gold (2023)',
    hobbies: 'Ballet, Painting, Reading fairytales',
    religion: 'Roman Catholic',
    profile_photo: null,
    is_deceased: 0,
    display_order: 10,
  },
  {
    id: 11,
    family_id: 1,
    full_name: 'Antonio Rodriguez Santos',
    nickname: 'Toni',
    slug: 'antonio-rodriguez-santos',
    gender: 'male',
    date_of_birth: '2015-01-30',
    date_of_death: null,
    place_of_birth: 'Manila, Philippines',
    biography: 'Toni is a happy and energetic boy who loves sports and outdoor adventures. He is the youngest member of the Rodriguez family.',
    occupation: 'Student',
    education: 'Kindergarten at Sunshine Learning Center',
    awards: null,
    hobbies: 'Soccer, Drawing, Building with Legos',
    religion: 'Roman Catholic',
    profile_photo: null,
    is_deceased: 0,
    display_order: 11,
  },
  {
    id: 12,
    family_id: 1,
    full_name: 'Elena Rodriguez',
    nickname: 'Lenlen',
    slug: 'elena-rodriguez',
    gender: 'female',
    date_of_birth: '1985-12-01',
    date_of_death: null,
    place_of_birth: 'Manila, Philippines',
    biography: 'Elena is a marine biologist dedicated to ocean conservation. She leads coral reef restoration projects in the Philippines and has been featured in several documentaries about marine ecology.',
    occupation: 'Marine Biologist',
    education: 'BS Marine Biology, University of the Philippines; PhD in Marine Ecology, James Cook University, Australia',
    awards: 'Ocean Hero Award (2020), Emerging Scientist Grant (2015)',
    hobbies: 'Scuba diving, Underwater photography, Surfing',
    religion: 'Roman Catholic',
    profile_photo: null,
    is_deceased: 0,
    display_order: 12,
  },

  // === Chen Dynasty (family_id: 2) ===
  {
    id: 13,
    family_id: 2,
    full_name: 'Chen Wei Ming',
    nickname: 'Uncle Ming',
    slug: 'chen-wei-ming',
    gender: 'male',
    date_of_birth: '1935-04-10',
    date_of_death: '2018-12-05',
    place_of_birth: 'Fujian, China',
    place_of_death: 'Singapore',
    biography: 'Chen Wei Ming was the pioneering patriarch who moved from Fujian to Singapore in the 1950s. He started a small trading business that eventually grew into one of Southeast Asia\'s largest textile conglomerates.',
    occupation: 'Entrepreneur / Business Magnate',
    education: 'Self-educated, Business Studies',
    awards: 'Singapore Business Pioneer Award (2000)',
    hobbies: 'Calligraphy, Mahjong, Tea ceremony',
    religion: 'Buddhism',
    profile_photo: null,
    is_deceased: 1,
    display_order: 1,
  },
  {
    id: 14,
    family_id: 2,
    full_name: 'Chen Li Hua',
    nickname: 'Auntie Hua',
    slug: 'chen-li-hua',
    gender: 'female',
    date_of_birth: '1940-08-25',
    date_of_death: null,
    place_of_birth: 'Singapore',
    biography: 'Li Hua is the family matriarch, a former concert pianist who studied at the Royal Academy of Music in London. She established the Chen Music Foundation which provides music education to children from underprivileged backgrounds.',
    occupation: 'Concert Pianist / Philanthropist',
    education: 'Royal Academy of Music, London',
    awards: 'Cultural Medallion (1990), Women of Distinction Award (2005)',
    hobbies: 'Piano, Gardening, Philately',
    religion: 'Buddhism',
    profile_photo: null,
    is_deceased: 0,
    display_order: 2,
  },
  {
    id: 15,
    family_id: 2,
    full_name: 'Chen Zhen Hao',
    nickname: 'Henry',
    slug: 'chen-zhen-hao',
    gender: 'male',
    date_of_birth: '1965-02-18',
    date_of_death: null,
    place_of_birth: 'Singapore',
    biography: 'Henry is the CEO of Chen Holdings, the family business. Under his leadership, the company has diversified into real estate, technology, and sustainable energy. He is also a board member of several charitable organizations.',
    occupation: 'CEO / Businessman',
    education: 'BSc Economics, London School of Economics; MBA, INSEAD',
    awards: 'Business Leader of the Year (2018)',
    hobbies: 'Golf, Wine collecting, Philanthropy',
    religion: 'Buddhism',
    profile_photo: null,
    is_deceased: 0,
    display_order: 3,
  },
  {
    id: 16,
    family_id: 2,
    full_name: 'Chen Mei Ling',
    nickname: 'Michelle',
    slug: 'chen-mei-ling',
    gender: 'female',
    date_of_birth: '1968-07-09',
    date_of_death: null,
    place_of_birth: 'Singapore',
    biography: 'Michelle is an award-winning architect known for her sustainable building designs. She has designed several landmark buildings in Singapore and is a passionate advocate for green urban development.',
    occupation: 'Architect',
    education: 'Bachelor of Architecture, National University of Singapore; Master of Sustainable Design, University of Cambridge',
    awards: 'Singapore Institute of Architects Gold Medal (2015), Green Building Award (2019)',
    hobbies: 'Yoga, Travel, Photography',
    religion: 'Buddhism',
    profile_photo: null,
    is_deceased: 0,
    display_order: 4,
  },
  {
    id: 17,
    family_id: 2,
    full_name: 'Chen Yu Jie',
    nickname: 'YJ',
    slug: 'chen-yu-jie',
    gender: 'male',
    date_of_birth: '1995-11-03',
    date_of_death: null,
    place_of_birth: 'Singapore',
    biography: 'YJ is a talented musician and composer who blends traditional Chinese instruments with modern electronic music. He has released three albums and performed at music festivals around the world.',
    occupation: 'Musician / Composer',
    education: 'Bachelor of Music, Berklee College of Music',
    awards: 'Best New Artist (2019), Global Music Award (2021)',
    hobbies: 'Music production, Cooking, Basketball',
    religion: 'Buddhism',
    profile_photo: null,
    is_deceased: 0,
    display_order: 5,
  },
  {
    id: 18,
    family_id: 2,
    full_name: 'Chen Jia Hui',
    nickname: 'Jia',
    slug: 'chen-jia-hui',
    gender: 'female',
    date_of_birth: '1998-04-22',
    date_of_death: null,
    place_of_birth: 'Singapore',
    biography: 'Jia is a medical researcher specializing in oncology. She is part of a groundbreaking research team working on immunotherapy treatments for cancer. She has published numerous papers in leading medical journals.',
    occupation: 'Medical Researcher / Oncologist',
    education: 'MBBS, National University of Singapore; PhD in Oncology, Johns Hopkins University',
    awards: 'Young Scientist Award (2023), Ruth L. Kirschstein Research Award (2022)',
    hobbies: 'Running, Reading sci-fi, Baking',
    religion: 'Buddhism',
    profile_photo: null,
    is_deceased: 0,
    display_order: 6,
  },
  {
    id: 19,
    family_id: 2,
    full_name: 'Chen Kai Xiang',
    nickname: 'Kai',
    slug: 'chen-kai-xiang',
    gender: 'male',
    date_of_birth: '2000-09-15',
    date_of_death: null,
    place_of_birth: 'Singapore',
    biography: 'Kai is a professional esports player and streamer who competes in international Dota 2 tournaments. He uses his platform to raise funds for children\'s hospitals across Asia.',
    occupation: 'Professional Esports Player / Streamer',
    education: 'Currently studying Business Administration part-time',
    awards: 'SEA Dota 2 Champion (2023), Most Inspiring Streamer (2022)',
    hobbies: 'Gaming, Fitness training, Watching anime',
    religion: 'Buddhism',
    profile_photo: null,
    is_deceased: 0,
    display_order: 7,
  },
  {
    id: 20,
    family_id: 2,
    full_name: 'Chen Xiao Yun',
    nickname: 'Xiao',
    slug: 'chen-xiao-yun',
    gender: 'female',
    date_of_birth: '2003-02-28',
    date_of_death: null,
    place_of_birth: 'Singapore',
    biography: 'Xiao is a rising star in the world of competitive figure skating. She has represented Singapore in multiple international competitions and dreams of competing in the Winter Olympics.',
    occupation: 'Figure Skater / Student',
    education: 'Student at Singapore Sports School',
    awards: 'Southeast Asian Games Gold Medal (2023), Junior World Championships Bronze (2022)',
    hobbies: 'Figure skating, Dancing, Fashion design',
    religion: 'Buddhism',
    profile_photo: null,
    is_deceased: 0,
    display_order: 8,
  },
]

export const relationships = [
  { id: 1, family_id: 1, member_id: 1, related_member_id: 2, relationship_type: 'spouse' },
  { id: 2, family_id: 1, member_id: 1, related_member_id: 3, relationship_type: 'child' },
  { id: 3, family_id: 1, member_id: 1, related_member_id: 4, relationship_type: 'child' },
  { id: 4, family_id: 1, member_id: 1, related_member_id: 5, relationship_type: 'child' },
  { id: 5, family_id: 1, member_id: 1, related_member_id: 6, relationship_type: 'child' },
  { id: 6, family_id: 1, member_id: 2, related_member_id: 3, relationship_type: 'child' },
  { id: 7, family_id: 1, member_id: 2, related_member_id: 4, relationship_type: 'child' },
  { id: 8, family_id: 1, member_id: 2, related_member_id: 5, relationship_type: 'child' },
  { id: 9, family_id: 1, member_id: 2, related_member_id: 6, relationship_type: 'child' },
  { id: 10, family_id: 1, member_id: 3, related_member_id: 7, relationship_type: 'child' },
  { id: 11, family_id: 1, member_id: 3, related_member_id: 8, relationship_type: 'child' },
  { id: 12, family_id: 1, member_id: 5, related_member_id: 12, relationship_type: 'child' },
  { id: 13, family_id: 1, member_id: 8, related_member_id: 11, relationship_type: 'child' },
  { id: 14, family_id: 1, member_id: 7, related_member_id: 9, relationship_type: 'child' },
  { id: 15, family_id: 1, member_id: 7, related_member_id: 10, relationship_type: 'child' },
]

export const timelineEvents = [
  { id: 1, family_id: 1, member_id: 1, title: 'Born in Manila', description: 'Alejandro Rodriguez Sr. was born in the district of Sampaloc, Manila.', event_date: '1920-03-15', event_type: 'birth' },
  { id: 2, family_id: 1, member_id: 1, title: 'Started Teaching Career', description: 'Began his first teaching position at Manila Central Elementary School.', event_date: '1942-06-01', event_type: 'career' },
  { id: 3, family_id: 1, member_id: 1, title: 'Became School Principal', description: 'Appointed principal of Quezon City National High School.', event_date: '1960-04-01', event_type: 'career' },
  { id: 4, family_id: 1, member_id: 1, title: 'Presidential Merit Award', description: 'Received the Presidential Merit Award for Education from President Corazon Aquino.', event_date: '1985-10-12', event_type: 'award' },
  { id: 5, family_id: 1, member_id: 1, title: 'Passed Away', description: 'Passed away peacefully at home surrounded by family at the age of 90.', event_date: '2010-11-02', event_type: 'death' },
  { id: 6, family_id: 1, member_id: 7, title: 'Birth of Miguel', description: 'Miguel Rodriguez, first child of Alejandro Jr., was born.', event_date: '1980-09-30', event_type: 'birth' },
  { id: 7, family_id: 1, member_id: 7, title: 'Founded TechStart', description: 'Miguel founded his first startup, TechStart, a mobile payments platform.', event_date: '2008-03-15', event_type: 'career' },
  { id: 8, family_id: 1, member_id: 7, title: 'Forbes 30 Under 30', description: 'Named to Forbes 30 Under 30 Asia list for contributions to fintech.', event_date: '2015-01-20', event_type: 'award' },
  { id: 9, family_id: 1, member_id: 7, title: 'Stanford MBA', description: 'Graduated with an MBA from Stanford Graduate School of Business.', event_date: '2019-06-15', event_type: 'education' },
  { id: 10, family_id: 1, member_id: 1, title: 'Married Maria', description: 'Alejandro married Maria Santos in a small ceremony in Manila.', event_date: '1948-05-20', event_type: 'milestone' },
  { id: 11, family_id: 2, member_id: 13, title: 'Arrived in Singapore', description: 'Chen Wei Ming arrived in Singapore with only $50 in his pocket.', event_date: '1955-07-01', event_type: 'milestone' },
  { id: 12, family_id: 2, member_id: 13, title: 'Founded Chen Trading Co.', description: 'Started a small trading company dealing in textiles and fabrics.', event_date: '1962-03-01', event_type: 'career' },
  { id: 13, family_id: 2, member_id: 15, title: 'Took Over Family Business', description: 'Henry Chen became CEO of Chen Holdings.', event_date: '2000-01-01', event_type: 'career' },
  { id: 14, family_id: 3, member_id: 1, title: 'First Thompson in America', description: 'William Thompson arrived in New York from Scotland.', event_date: '1845-04-01', event_type: 'milestone' },
]

export const mediaItems = [
  { id: 1, family_id: 1, member_id: 1, file_name: 'alejandro_wedding.jpg', file_path: '/images/placeholder.jpg', caption: 'Alejandro and Maria on their wedding day, 1948', is_cover: 1, file_type: 'image' },
  { id: 2, family_id: 1, member_id: 2, file_name: 'maria_portrait.jpg', file_path: '/images/placeholder.jpg', caption: 'Maria in her garden, 1985', is_cover: 1, file_type: 'image' },
  { id: 3, family_id: 1, member_id: 1, file_name: 'family_reunion_1980.jpg', file_path: '/images/placeholder.jpg', caption: 'Rodriguez Family Reunion, 1980', is_cover: 0, file_type: 'image' },
  { id: 4, family_id: 1, member_id: 3, file_name: 'alex_graduation.jpg', file_path: '/images/placeholder.jpg', caption: 'Alex receiving his PhD, 1985', is_cover: 1, file_type: 'image' },
  { id: 5, family_id: 1, member_id: 7, file_name: 'miguel_forbes.jpg', file_path: '/images/placeholder.jpg', caption: 'Miguel at Forbes 30 Under 30 ceremony', is_cover: 1, file_type: 'image' },
  { id: 6, family_id: 1, member_id: null, file_name: 'rodriguez_home.jpg', file_path: '/images/placeholder.jpg', caption: 'The Rodriguez family home in Manila', is_cover: 0, file_type: 'image' },
]

export const messages = [
  { id: 1, family_id: 1, member_id: 1, visitor_name: 'Juan Dela Cruz', message: 'Don Alejo was my principal in high school. He was a kind and firm leader who inspired me to become a teacher myself. Rest in peace, Sir.', is_approved: 1, created_at: '2024-01-15T10:30:00Z' },
  { id: 2, family_id: 1, member_id: 1, visitor_name: 'Maria Santos', message: 'Thank you for your service to education. You have touched so many lives.', is_approved: 1, created_at: '2024-02-20T14:15:00Z' },
  { id: 3, family_id: 1, member_id: 2, visitor_name: 'Ana Rodriguez', message: 'Lola Mary\'s adobo recipe is still the best. We miss you so much.', is_approved: 1, created_at: '2024-03-10T09:00:00Z' },
  { id: 4, family_id: 1, member_id: 5, visitor_name: 'John Smith', message: 'Carlos designed our family home. He was a genius and a gentleman. He will be missed.', is_approved: 1, created_at: '2024-04-05T16:45:00Z' },
  { id: 5, family_id: 1, member_id: 5, visitor_name: 'Marie Lopez', message: 'Condolences to the Rodriguez family. Caloy was a great architect and an even better friend.', is_approved: 0, created_at: '2024-05-12T11:20:00Z' },
  { id: 6, family_id: 2, member_id: 13, visitor_name: 'David Tan', message: 'Uncle Ming was a titan of industry but always had time for the little people. An inspiration.', is_approved: 1, created_at: '2024-06-01T08:30:00Z' },
]

export const statsData = {
  total_families: 3,
  total_members: 20,
  total_photos: 6,
  total_videos: 0,
  total_messages: 6,
  pending_messages: 1,
  total_qr_scans: 1284,
}
